# Generated by Django 5.0.1 on 2024-01-24 23:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('_ingredient_id', models.AutoField(primary_key=True, serialize=False)),
                ('_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('_restaurant_id', models.AutoField(primary_key=True, serialize=False)),
                ('_name', models.CharField(max_length=200)),
                ('_location', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('_recipe_id', models.AutoField(primary_key=True, serialize=False)),
                ('_title', models.CharField(max_length=200)),
                ('_instructions', models.TextField()),
                ('_ingredients', models.ManyToManyField(to='ServerPrototypeApp.ingredient')),
                ('_restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ServerPrototypeApp.restaurant')),
            ],
        ),
    ]
